//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KANEC
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Спрос.
    /// </summary>
    // *** Start programmer edit section *** (Спрос CustomAttributes)

    // *** End programmer edit section *** (Спрос CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СпросE", new string[] {
            "Номер as \'Номер\'",
            "Цена as \'Цена\'",
            "КатегорНомера as \'Категор номера\'",
            "ЗанятВМесяц as \'Занят в месяц\'",
            "Юридич as \'Юридич\'",
            "БроньЧерСайт as \'Бронь чер сайт\'",
            "СкПриДлитПрожив as \'Ск при длит прожив\'",
            "СкДР as \'Ск ДР\'",
            "СкВторНомер as \'Ск втор номер\'",
            "СуммСоСкид as \'Сумм со скид\'",
            "Маркетолог as \'Маркетолог\'"})]
    [MasterViewDefineAttribute("СпросE", "Маркетолог", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "")]
    [View("СпросL", new string[] {
            "Номер as \'Номер\'",
            "Цена as \'Цена\'",
            "КатегорНомера as \'Категор номера\'",
            "ЗанятВМесяц as \'Занят в месяц\'",
            "Юридич as \'Юридич\'",
            "БроньЧерСайт as \'Бронь чер сайт\'",
            "СкПриДлитПрожив as \'Ск при длит прожив\'",
            "СкДР as \'Ск ДР\'",
            "СкВторНомер as \'Ск втор номер\'",
            "СуммСоСкид as \'Сумм со скид\'"})]
    public class Спрос : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private int fЦена;
        
        private int fКатегорНомера;
        
        private int fЗанятВМесяц;
        
        private bool fЮридич;
        
        private bool fБроньЧерСайт;
        
        private bool fСкПриДлитПрожив;
        
        private bool fСкДР;
        
        private bool fСкВторНомер;
        
        private int fСуммСоСкид;
        
        private IIS.KANEC.Маркетолог fМаркетолог;
        
        // *** Start programmer edit section *** (Спрос CustomMembers)

        // *** End programmer edit section *** (Спрос CustomMembers)

        
        /// <summary>
        /// БроньЧерСайт.
        /// </summary>
        // *** Start programmer edit section *** (Спрос.БроньЧерСайт CustomAttributes)

        // *** End programmer edit section *** (Спрос.БроньЧерСайт CustomAttributes)
        public virtual bool БроньЧерСайт
        {
            get
            {
                // *** Start programmer edit section *** (Спрос.БроньЧерСайт Get start)

                // *** End programmer edit section *** (Спрос.БроньЧерСайт Get start)
                bool result = this.fБроньЧерСайт;
                // *** Start programmer edit section *** (Спрос.БроньЧерСайт Get end)

                // *** End programmer edit section *** (Спрос.БроньЧерСайт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Спрос.БроньЧерСайт Set start)

                // *** End programmer edit section *** (Спрос.БроньЧерСайт Set start)
                this.fБроньЧерСайт = value;
                // *** Start programmer edit section *** (Спрос.БроньЧерСайт Set end)

                // *** End programmer edit section *** (Спрос.БроньЧерСайт Set end)
            }
        }
        
        /// <summary>
        /// ЗанятВМесяц.
        /// </summary>
        // *** Start programmer edit section *** (Спрос.ЗанятВМесяц CustomAttributes)

        // *** End programmer edit section *** (Спрос.ЗанятВМесяц CustomAttributes)
        public virtual int ЗанятВМесяц
        {
            get
            {
                // *** Start programmer edit section *** (Спрос.ЗанятВМесяц Get start)

                // *** End programmer edit section *** (Спрос.ЗанятВМесяц Get start)
                int result = this.fЗанятВМесяц;
                // *** Start programmer edit section *** (Спрос.ЗанятВМесяц Get end)

                // *** End programmer edit section *** (Спрос.ЗанятВМесяц Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Спрос.ЗанятВМесяц Set start)

                // *** End programmer edit section *** (Спрос.ЗанятВМесяц Set start)
                this.fЗанятВМесяц = value;
                // *** Start programmer edit section *** (Спрос.ЗанятВМесяц Set end)

                // *** End programmer edit section *** (Спрос.ЗанятВМесяц Set end)
            }
        }
        
        /// <summary>
        /// КатегорНомера.
        /// </summary>
        // *** Start programmer edit section *** (Спрос.КатегорНомера CustomAttributes)

        // *** End programmer edit section *** (Спрос.КатегорНомера CustomAttributes)
        public virtual int КатегорНомера
        {
            get
            {
                // *** Start programmer edit section *** (Спрос.КатегорНомера Get start)

                // *** End programmer edit section *** (Спрос.КатегорНомера Get start)
                int result = this.fКатегорНомера;
                // *** Start programmer edit section *** (Спрос.КатегорНомера Get end)

                // *** End programmer edit section *** (Спрос.КатегорНомера Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Спрос.КатегорНомера Set start)

                // *** End programmer edit section *** (Спрос.КатегорНомера Set start)
                this.fКатегорНомера = value;
                // *** Start programmer edit section *** (Спрос.КатегорНомера Set end)

                // *** End programmer edit section *** (Спрос.КатегорНомера Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Спрос.Номер CustomAttributes)

        // *** End programmer edit section *** (Спрос.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Спрос.Номер Get start)

                // *** End programmer edit section *** (Спрос.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Спрос.Номер Get end)

                // *** End programmer edit section *** (Спрос.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Спрос.Номер Set start)

                // *** End programmer edit section *** (Спрос.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Спрос.Номер Set end)

                // *** End programmer edit section *** (Спрос.Номер Set end)
            }
        }
        
        /// <summary>
        /// СкВторНомер.
        /// </summary>
        // *** Start programmer edit section *** (Спрос.СкВторНомер CustomAttributes)

        // *** End programmer edit section *** (Спрос.СкВторНомер CustomAttributes)
        public virtual bool СкВторНомер
        {
            get
            {
                // *** Start programmer edit section *** (Спрос.СкВторНомер Get start)

                // *** End programmer edit section *** (Спрос.СкВторНомер Get start)
                bool result = this.fСкВторНомер;
                // *** Start programmer edit section *** (Спрос.СкВторНомер Get end)

                // *** End programmer edit section *** (Спрос.СкВторНомер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Спрос.СкВторНомер Set start)

                // *** End programmer edit section *** (Спрос.СкВторНомер Set start)
                this.fСкВторНомер = value;
                // *** Start programmer edit section *** (Спрос.СкВторНомер Set end)

                // *** End programmer edit section *** (Спрос.СкВторНомер Set end)
            }
        }
        
        /// <summary>
        /// СкДР.
        /// </summary>
        // *** Start programmer edit section *** (Спрос.СкДР CustomAttributes)

        // *** End programmer edit section *** (Спрос.СкДР CustomAttributes)
        public virtual bool СкДР
        {
            get
            {
                // *** Start programmer edit section *** (Спрос.СкДР Get start)

                // *** End programmer edit section *** (Спрос.СкДР Get start)
                bool result = this.fСкДР;
                // *** Start programmer edit section *** (Спрос.СкДР Get end)

                // *** End programmer edit section *** (Спрос.СкДР Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Спрос.СкДР Set start)

                // *** End programmer edit section *** (Спрос.СкДР Set start)
                this.fСкДР = value;
                // *** Start programmer edit section *** (Спрос.СкДР Set end)

                // *** End programmer edit section *** (Спрос.СкДР Set end)
            }
        }
        
        /// <summary>
        /// СкПриДлитПрожив.
        /// </summary>
        // *** Start programmer edit section *** (Спрос.СкПриДлитПрожив CustomAttributes)

        // *** End programmer edit section *** (Спрос.СкПриДлитПрожив CustomAttributes)
        public virtual bool СкПриДлитПрожив
        {
            get
            {
                // *** Start programmer edit section *** (Спрос.СкПриДлитПрожив Get start)

                // *** End programmer edit section *** (Спрос.СкПриДлитПрожив Get start)
                bool result = this.fСкПриДлитПрожив;
                // *** Start programmer edit section *** (Спрос.СкПриДлитПрожив Get end)

                // *** End programmer edit section *** (Спрос.СкПриДлитПрожив Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Спрос.СкПриДлитПрожив Set start)

                // *** End programmer edit section *** (Спрос.СкПриДлитПрожив Set start)
                this.fСкПриДлитПрожив = value;
                // *** Start programmer edit section *** (Спрос.СкПриДлитПрожив Set end)

                // *** End programmer edit section *** (Спрос.СкПриДлитПрожив Set end)
            }
        }
        
        /// <summary>
        /// СуммСоСкид.
        /// </summary>
        // *** Start programmer edit section *** (Спрос.СуммСоСкид CustomAttributes)

        // *** End programmer edit section *** (Спрос.СуммСоСкид CustomAttributes)
        public virtual int СуммСоСкид
        {
            get
            {
                // *** Start programmer edit section *** (Спрос.СуммСоСкид Get start)

                // *** End programmer edit section *** (Спрос.СуммСоСкид Get start)
                int result = this.fСуммСоСкид;
                // *** Start programmer edit section *** (Спрос.СуммСоСкид Get end)

                // *** End programmer edit section *** (Спрос.СуммСоСкид Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Спрос.СуммСоСкид Set start)

                // *** End programmer edit section *** (Спрос.СуммСоСкид Set start)
                this.fСуммСоСкид = value;
                // *** Start programmer edit section *** (Спрос.СуммСоСкид Set end)

                // *** End programmer edit section *** (Спрос.СуммСоСкид Set end)
            }
        }
        
        /// <summary>
        /// Цена.
        /// </summary>
        // *** Start programmer edit section *** (Спрос.Цена CustomAttributes)

        // *** End programmer edit section *** (Спрос.Цена CustomAttributes)
        public virtual int Цена
        {
            get
            {
                // *** Start programmer edit section *** (Спрос.Цена Get start)

                // *** End programmer edit section *** (Спрос.Цена Get start)
                int result = this.fЦена;
                // *** Start programmer edit section *** (Спрос.Цена Get end)

                // *** End programmer edit section *** (Спрос.Цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Спрос.Цена Set start)

                // *** End programmer edit section *** (Спрос.Цена Set start)
                this.fЦена = value;
                // *** Start programmer edit section *** (Спрос.Цена Set end)

                // *** End programmer edit section *** (Спрос.Цена Set end)
            }
        }
        
        /// <summary>
        /// Юридич.
        /// </summary>
        // *** Start programmer edit section *** (Спрос.Юридич CustomAttributes)

        // *** End programmer edit section *** (Спрос.Юридич CustomAttributes)
        public virtual bool Юридич
        {
            get
            {
                // *** Start programmer edit section *** (Спрос.Юридич Get start)

                // *** End programmer edit section *** (Спрос.Юридич Get start)
                bool result = this.fЮридич;
                // *** Start programmer edit section *** (Спрос.Юридич Get end)

                // *** End programmer edit section *** (Спрос.Юридич Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Спрос.Юридич Set start)

                // *** End programmer edit section *** (Спрос.Юридич Set start)
                this.fЮридич = value;
                // *** Start programmer edit section *** (Спрос.Юридич Set end)

                // *** End programmer edit section *** (Спрос.Юридич Set end)
            }
        }
        
        /// <summary>
        /// Спрос.
        /// </summary>
        // *** Start programmer edit section *** (Спрос.Маркетолог CustomAttributes)

        // *** End programmer edit section *** (Спрос.Маркетолог CustomAttributes)
        [PropertyStorage(new string[] {
                "Маркетолог"})]
        [NotNull()]
        public virtual IIS.KANEC.Маркетолог Маркетолог
        {
            get
            {
                // *** Start programmer edit section *** (Спрос.Маркетолог Get start)

                // *** End programmer edit section *** (Спрос.Маркетолог Get start)
                IIS.KANEC.Маркетолог result = this.fМаркетолог;
                // *** Start programmer edit section *** (Спрос.Маркетолог Get end)

                // *** End programmer edit section *** (Спрос.Маркетолог Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Спрос.Маркетолог Set start)

                // *** End programmer edit section *** (Спрос.Маркетолог Set start)
                this.fМаркетолог = value;
                // *** Start programmer edit section *** (Спрос.Маркетолог Set end)

                // *** End programmer edit section *** (Спрос.Маркетолог Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СпросE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпросE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпросE", typeof(IIS.KANEC.Спрос));
                }
            }
            
            /// <summary>
            /// "СпросL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпросL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпросL", typeof(IIS.KANEC.Спрос));
                }
            }
        }
    }
}
